### ISSUE TITLE
[BUG] - Getting error whil building using vite-ssg

### ISSUE THREAD

**Issue by sujit-baniya** [vueup/vue-quill#156]
**Version**
@vueup/vue-quill version [e.g. 1.0.0-beta.7]

**Describe the bug**
I'm using vite-ssg for server side building of app. When I tried to build the project, quill is throwing this error

```js
ReferenceError: document is not defined
    at Object.<anonymous> (/web/node_modules/.pnpm/quill@1.3.7/node_modules/quill/dist/quill.js:7661:12)
    at __webpack_require__ (/web/node_modules/.pnpm/quill@1.3.7/node_modules/quill/dist/quill.js:36:30)
    at Object.<anonymous> (/web/node_modules/.pnpm/quill@1.3.7/node_modules/quill/dist/quill.js:1030:1)
    at __webpack_require__ (/web/node_modules/.pnpm/quill@1.3.7/node_modules/quill/dist/quill.js:36:30)
    at Object.<anonymous> (/web/node_modules/.pnpm/quill@1.3.7/node_modules/quill/dist/quill.js:5655:14)
    at __webpack_require__ (/web/node_modules/.pnpm/quill@1.3.7/node_modules/quill/dist/quill.js:36:30)
    at Object.<anonymous> (/web/node_modules/.pnpm/quill@1.3.7/node_modules/quill/dist/quill.js:10045:13)
    at __webpack_require__ (/web/node_modules/.pnpm/quill@1.3.7/node_modules/quill/dist/quill.js:36:30)
    at Object.<anonymous> (/web/node_modules/.pnpm/quill@1.3.7/node_modules/quill/dist/quill.js:11557:18)
    at __webpack_require__ (/web/node_modules/.pnpm/quill@1.3.7/node_modules/quill/dist/quill.js:36:30)
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.
```
Please suggest some ways to fix this issue

**Comment by vuejstime** [comment]
same issue

**Comment by BigKamil5** [comment]
Any update on this one??

**Comment by BigKamil5** [comment]
![image](https://user-images.githubusercontent.com/37780630/176123829-3b778045-ffda-4666-9a22-4b96957ab292.png)

You can try async component with cleint only tag. Seems to be working this way

**Comment by luthfimasruri** [comment]
You can use [defineAsyncComponent](https://vuejs.org/guide/components/async.html)
``` js
import { defineAsyncComponent } from 'vue'
import Loading from './components/Loading.vue'

const QuillEditor = defineAsyncComponent({
  loader: () =>
    import('@vueup/vue-quill').then((VueQuill) => VueQuill.QuillEditor),
  loadingComponent: Loading,
})
```
